import React from 'react';
import TopBar from './topBar';
import Sidebar from './sideBar';
import styles from './styles/page.module.css';
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className={styles.container}>
          <TopBar />
          <div className={styles.contentContainer}>
            <Sidebar />
            <div className={styles.mainContent}>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
};

export default Layout;
